---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spr-sa
automountServiceAccountToken: false

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-pod-reader
rules:
  - apiGroups: ""
    resources:
      - secrets
    verbs:
      - get
      - watch
      - list
  - apiGroups: ""
    resources:
      - pod
    verbs:
      - get
      - watch
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-pod-reader-binding
subjects:
  - kind: ServiceAccount
    name: spr-sa
roleRef:
  kind: Role
  name: secret-pod-reader

