apiVersion: v2
name: nopcommerce
description: A Helm chart for Kubernetes
type: application
version: 0.1.1
appVersion: "1.16.0"
home: https://directdevops.blog
icon: https://directdevops.blog/wp-content/uploads/2019/01/cropped-directdevops.png
sources:
  - "https://github.com/asquarezone/CompleteK8s/tree/master/Sep23/CKA/helm/nopcommerce"
maintainers:
  - name: khajaibrahim
    email: admin@khaja.tech
deprecated: false
kubeVersion: ">1.24.0"

