---
apiVersion: v1
kind: Pod
metadata:
  name: actvity1
spec:
  containers:
    - name: alpine
      image: alpine
      command:
        - sleep
        - 1d
  initContainers:
    - name: initalp
      image: alpine
      command:
        - sleep
        - 15s
        - "&&"
        - exit
        - "104"

