---
apiVersion: v1
kind: Pod
metadata:
  name: matchingna
spec:
  affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: diskspeed
              operator: In
              values:
                - high
                - medium
  containers:
    - name: mycontainer
      image: nginx