---
apiVersion: v1
kind: Pod
metadata:
  name: nonmatchinghard
spec:
  affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: diskspeed
              operator: In
              values:
                - low
                - magnetic
  containers:
    - name: mycontainer
      image: nginx