---
apiVersion: v1
kind: Pod
metadata:
  name: nonmatchingsoft
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: diskspeed
                operator: In
                values:
                  - low
                  - magnetic
          weight: 1
  containers:
    - name: mycontainer
      image: nginx