apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: db
spec:
  containers:
    - name: myapp
      image: postgres:16
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_PASSWORD
          value: nop12345
        - name: POSTGRES_USER
          value: nop
        - name: POSTGRES_DB
          value: nop
  volumes:
    - name: nopvol
      persistentVolumeClaim:
        claimName: nop-pvc
