---
apiVersion: v1
kind: Pod
metadata:
  name: actvity2
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins:lts-jdk11
      resources:
        requests:
          memory: 100Mi
        limits:
          memory: 256Mi
          cpu: 0.05

