---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: nginx
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
    