resources:
  - ../../base

namespace: dev
images:
  - name: nginx
    newTag: latest

patches:
  - path: deployment.yaml

configMapGenerator:
  - name: debug
    files:
      - application.properties
      - debug